### ISSUE TITLE
Update governance doc

### ISSUE THREAD

**Issue by sjsrey** [pysal/governance#4]
- [ ] mediation process
- [x] formalize the steering council

See [dev meeting 2022-02-04]( https://hackmd.io/NVE_NKDVTE6wkb7PD3pAlg)

Having a revision to vote on at the 2022-03-04 meeting would be a good target.

**Comment by knaaptime** [comment]
need to update docs to revise the definition of the council as the elected members rather than all core devs

**Comment by knaaptime** [comment]
- rm wording re "council chair"

**Comment by jGaboardi** [comment]
I think this can be closed out now?

@knaaptime @martinfleis @sjsrey

**Comment by jGaboardi** [comment]
Closing out after merge of #9
