### ISSUE TITLE
steering council meeting schedule

### ISSUE THREAD

**Issue by jGaboardi** [pysal/governance#8]
Somehow our steering council meetings got deleted from the PySAL calendar. Their tentative dates are supposed to be Wednesdays following the monthly PySAL dev meetings at 12 Eastern time (4GMT/9Pacific).

@knaaptime Are you available on Friday this week to meet during that time slot to make up for our missed meeting today? @martinfleis and I are both available.

**Comment by knaaptime** [comment]
im traveling until next tuesday but i could maybe squeeze something on friday. when are you thinking?

**Comment by martinfleis** [comment]
We can postpone it, there's nothing pressing right now. But we should find a date for it anyway. 

I also have a lot of travelling coming up but I should be able to find time during the last week of June. Otherwise it will have to wait for the second half of July.

**Comment by jGaboardi** [comment]
Let's plan on sometime during the last week of June. In the meantime, how does pysal/libpysal#468 look? Is this something like what we are aiming for?

**Comment by jGaboardi** [comment]
Closing since this was 2 years ago.
